
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import path from 'path';
import fs from 'fs';

export const app = express();
app.use(helmet());
app.use(cors());
app.use(express.json());

// Health
app.get('/api/health', (_req, res) => res.json({ ok: true }));

// Serve PR metrics JSON generated by GitHub Action
const metricsDir = path.resolve(process.cwd(), 'metrics');
if (fs.existsSync(metricsDir)) {
  app.use('/metrics', express.static(metricsDir));
}

// Simple homepage
app.get('/', (_req, res) => res.send('Copilot-only PR Review Demo — API is up.')); 
